### ISSUE TITLE
API Limit

### ISSUE THREAD

**Issue by afang** [Medium/medium-api-docs#10]
What is the limit to the # of calls you can make using a self-issued access token?

**Comment by majelbstoat** [comment]
There is no limit specific to self-issued access tokens. However, Medium does use a dynamic limit for post creation, the details of which change from time to time and are not public. If you are a not a bad actor, you should very rarely run into this limit.

**Comment by majelbstoat** [comment]
Closed as "not an issue".

**Comment by srccd** [comment]
I may have borked something, but I hit the rate limit with a self-issued token after about 15 "posts" (create post) calls and a few "me" calls.

"User ... has reached the rate limit for publishing today"

Using the Python SDK.

Maybe that "dynamic limit" is very strict on new-ish accounts, but 15 is painful. I know it's not a documented limit, but is it really that tight?
