### ISSUE TITLE
[REQUEST] Endpoint to retrieve list of all authenticated user's posts (including drafts)

### ISSUE THREAD

**Issue by oddlyfunctional** [Medium/medium-api-docs#100]
Hi, I have an idea for an app to monitor a user's productivity based on how many words he wrote per day. Although it is possible to retrieve the published posts using the RSS feed (not ideal, but doable), there's no API to retrieve drafts for an authenticated user, which makes an app like this impossible.
It would be great if you could provide at least a read-only endpoint to retrieve all of the authenticated user's posts, including drafts, or at least all posts in the last 24h.

**Comment by MediumEng** [comment]
Thank you for the suggestion. Unfortunately no enhancements to the API are planned at this time.
