### ISSUE TITLE
Unable to get access token - Getting access denied as response

### ISSUE THREAD

**Issue by iampraba** [Medium/medium-api-docs#102]
When i tried to get access token via [authentication end point](https://medium.com/m/oauth/authorize) using short-lived authorization code, getting html as response instead of access token response json. Anyone else facing the same issue? Please throw some light on this, what went wrong! 

Check the screenshot for better understanding of error response. Thanks!

![screen shot 2017-06-19 at 10 08 23 am](https://user-images.githubusercontent.com/6869628/27270039-110651d0-54d9-11e7-9f89-582848387ab8.png)

**Comment by MediumEng** [comment]
Closing some old issues for repo maintenance. Feel free to write yourfriends@medium.com if you are having issues with authentication.
