### ISSUE TITLE
Posting tag "sport", response is "sports"

### ISSUE THREAD

**Issue by adriangodong** [Medium/medium-api-docs#104]
I'm following the documentation and after successfully creating a new post that contains "sport" as one of the three tags, the response back renamed the tag as "sports". Is this is an expected feature?

Test fix for .NET SDK: https://github.com/adriangodong/medium-sdk-dotnet/commit/54d847bb3f0355dc55d6dd0954e0bc790348eb9f

**Comment by MediumEng** [comment]
Yes this is expected. Singular/plural tags are normalized to have the same tag slug (except in explicitly prevented cases where that changes the meaning).
