### ISSUE TITLE
Social network "Connections" support in publish API required

### ISSUE THREAD

**Issue by tim-yao** [Medium/medium-api-docs#108]
I would like to use this API to publish post and share links on Facebook & Twitter as well.

I can do the post sharing in Medium website post publish UI. But I think it's not supported in API because I can't find any "share" or "connections" things in the API "Posts" resources.

Is there a way to achieve my above requirement?

**Comment by duongthanhtung** [comment]
oke

**Comment by MediumEng** [comment]
Sharing to twitter and facebook is not supported via the API.
