### ISSUE TITLE
Call back url issue

### ISSUE THREAD

**Issue by trumpnewscenter** [Medium/medium-api-docs#110]
Hello everybody!

I'm new at GitHub so sorry if I put this in wrong place.

So lets start from begining.

I created account in SNAP (Social network autoposter for Wordpress) and open account on Medium and get my client id and client secret number.

After that I yust need to click "Authorise your account", but whatever that I do I alway get as result page 400 and message from Medium: "We didn’t understand your request. Find something interesting to read. Check the site status.".

First I thougt that it was my mistake, that I have done some mistake in my steps for authorisation but then I discover that problem lies in Medium server response.

What happends is something like this: We give Callback URLs something like this:

http://wordpress.com/wp-admin/admin.php?page=sometest

After that I got response from Medium

https://medium.com/m/oauth/authorize?client_id= ...(the link is very long so I skip this part, important thing is hapenning after redirect_uri)... &redirect_uri=http%3A%2F%2Fwordpress.com%2Fwp-admin%2Fadmin.php.

As you can see from example from above what happend that server response convert / into %2F and :// into %3A%2F%2F. The ? mark and part behind this does not exist in url. 

Because of this any server response from Medim for aplication authorization is not correct.

When I manualy change response as it should be I got access to aplication.

I hope that you will repair this soon so that it will work as it should be.

I also hope that I help to someone else.

You can always found me on [trumpnews.center](http://trumpnews.center/)

Regards Trump News

**Comment by MediumEng** [comment]
This sounds like an issue with the SNAP plugin's integration.

> As you can see from example from above what happend that server response convert / into %2F and :// into %3A%2F%2F. The ? mark and part behind this does not exist in url.

This is the correct URL encoding behavior for query parameters.
