### ISSUE TITLE
Can I get your all public post from my Medium account via API

### ISSUE THREAD

**Issue by magebay99** [Medium/medium-api-docs#111]
Hello Support Team

I wonder how can I use the API connection to feed all my blog post from my medium account into HTML format as blog channel on our website?
Looking forward to hearing from you.

Thanks in advance!
Calvin

**Comment by FEW162626** [comment]
I don't know what accoi nt has been credited in my email address.  pl us I
don't know what medium account is.
please ha bc e an developer contact to expl ain gow this occoured

**Comment by MediumEng** [comment]
You may be able to use your account's RSS feed for this.
