### ISSUE TITLE
Please add the possibility to fetch the bookmarks of an authenticated user

### ISSUE THREAD

**Issue by AndreyPoznyak** [Medium/medium-api-docs#113]
I know it was asked a few times already but still there is no result though it really seems to be useful.

Currently API allows only to fetch publications - /me/publications
In addition please allow to get the list of user's bookmarks -  /browse/bookmarks
C'mon guys!

**Comment by mczlatan** [comment]
+1

**Comment by kwinyyyc** [comment]
Looking for the same. Currently API is too limited and hardly do anything with it. Please consider adding more endpoints to your OpenAPI!

**Comment by LeandroTk** [comment]
This would be great!

Another Issue about this Bookmark endpoint [here](https://github.com/Medium/medium-api-docs/issues/50).

**Comment by anjakammer** [comment]
+1

**Comment by spyou** [comment]
+1

**Comment by Nezne1k4** [comment]
+1

**Comment by bansal-rahul** [comment]
+1

**Comment by bansal-rahul** [comment]
Hi, i really want this feature and even interested in contributing through code. Can you guide me in doing so?

**Comment by Frondor** [comment]
We need it :octocat:

**Comment by melwinalm** [comment]
+1

**Comment by SivaramSS** [comment]
Bookmarks api please!!

**Comment by ajduke** [comment]
+1 👍

**Comment by AkiraEndoGroup** [comment]
+1

**Comment by mini-gui** [comment]
+1

**Comment by bntzio** [comment]
+1

**Comment by MediumEng** [comment]
There are currently no plans for this.
