### ISSUE TITLE
How to use self issued access token?

### ISSUE THREAD

**Issue by selfup** [Medium/medium-api-docs#116]
All SDKs force you to use CLIENT_ID and CLIENT_SECRET to successfully create the client. How does one publish a post using just a self issued token? Should be trivial but I can't find this information anywhere 🤔

**Comment by MrToph** [comment]
You still need to create an app within medium. You can find it in the settings.

Then you just create any self issued access token and set it via `.setAccessToken`, as in the following:
```jsx
const mediumClient = new medium.MediumClient({
  clientId: 'xxx',
  clientSecret: 'yyyyyyy',
})

const accessToken =
  'zzzzzzzzzzzzzzz'

mediumClient.setAccessToken(accessToken)
```

**Comment by selfup** [comment]
I was hoping to make an npm package that would be sort of like Jekyll that would post to Medium. I guess in this case I would have to ask users to create ENV vars that I would read (both app tokens and self issued token) since there would not be a web interface.

Thanks for the information!
