### ISSUE TITLE
Is getting all posts associated with a particular publication possible?

### ISSUE THREAD

**Issue by mjvcallibrity** [Medium/medium-api-docs#118]
Reading through your documentation I see that you allow for creating a new post that will be associated with a specific publication. Will

`GET https://api.medium.com/v1/publications/{{publicationId}}/posts`

also work, in that it will return all of the posts associated with a given publication?

**Comment by rodrigoreis22** [comment]
I also want to get all posts under a publication, using the url you described didn't work.

**Comment by mjvcallibrity** [comment]
Can anyone from the Medium team comment on this? There are at least 2 or 3 other issues open that speak to wanting this kind of functionality, but no definitive answer from the Medium team whether or not this is on their feature roadmap.

**Comment by samrap** [comment]
Bump. Looking to pull in the titles for my articles so I can link to them from a web page. My guess is they will not provide this functionality, as it opens up the ability for implementing third party clients that could potentially take away from the amount of visitors on their actual site.

At the very _least_, I would hope to be able to pull a title, link, and excerpt of a post via the API.

**Comment by erellsworth** [comment]
This is the only reason I even looked at the Medium API. I want to be able to pull a list of stories from my publication so I can automate Tweeting links to the stories.

**Comment by altcointrading** [comment]
+1

**Comment by jamesnesfield** [comment]
+1

**Comment by creaux** [comment]
+1

**Comment by cksachdev** [comment]
+1

**Comment by owendall** [comment]
+1

**Comment by MediumEng** [comment]
We provide an RSS feed for each publication, e.g. medium.com/feed/electric-literature, for this purpose
