### ISSUE TITLE
Get claps for an article?

### ISSUE THREAD

**Issue by loganpowell** [Medium/medium-api-docs#119]
Is there a way to get the number of claps for an article?

**Comment by TamimiGitHub** [comment]
Bump +1 I'd like to know if there is an API to get the number of claps for an article.

**Comment by SrdjanCosicPrica** [comment]
+1 I would also like the ability to get the total amount of claps for all of my articles.

**Comment by faraazc** [comment]
+1 its a must required feature

**Comment by moritzfelipe** [comment]
+1 Would be an important feature to build more upon medium platform

**Comment by brennanerbz** [comment]
+1

**Comment by flaviusburca** [comment]
+1

**Comment by javadhelali** [comment]
+1

**Comment by Cphilo** [comment]
+1

**Comment by taiwei426** [comment]
+1

**Comment by MediumEng** [comment]
No this feature is not supported
