### ISSUE TITLE
Documentation for tags field when creating a post.

### ISSUE THREAD

**Issue by adactio** [Medium/medium-api-docs#12]
In the documentation for the /posts method, it currently lists the "tags" field as:

string[]

...but if you send a string, the post fails. It looks like "tags" must always be an array.

**Comment by majelbstoat** [comment]
ah. Yes, `string[]` means "string array". Compare to other fields on that request, which are of type `string`.

**Comment by majelbstoat** [comment]
I can make this clearer.

**Comment by adactio** [comment]
@majelbstoat Much appreciated!
