### ISSUE TITLE
Fetch publication's post 

### ISSUE THREAD

**Issue by srsandy** [Medium/medium-api-docs#121]
Can you pls tell me a way to Fetch the publication all post's

**Comment by brunopulis** [comment]
Hello, @srsandy , Medium does not have an endpoint to search for the /GET requests. What can be done is to use RSS to search for posts. Like this: `https://medium.com/feed/@youruser`

**Comment by srsandy** [comment]
Thanks @brunopulis :)

**Comment by SarasArya** [comment]
Hi @brunopulis Even if I comment it becomes a story in Medium. Any way I can remove those?

**Comment by brunopulis** [comment]
Hi @SarasArya hmm, i will search about this.

**Comment by MediumEng** [comment]
Clsoing as duplicate of https://github.com/Medium/medium-api-docs/issues/118
