### ISSUE TITLE
Incorrect status code listed in Publications dcoumentation

### ISSUE THREAD

**Issue by FrankDrebin893** [Medium/medium-api-docs#123]
Hi, I'm sorry if it's incorrect to create an issue regarding this, probably very minor.

In the documentation here at https://github.com/Medium/medium-api-docs the possible status codes listed under 3.2 (Publications) are

401 Unauthorized
401 Forbidden

It should probably be 403 Forbidden there right?

**Comment by MediumEng** [comment]
Yep! Thank you. This was fixed in a PR that we let sit around unreviewed for way too long https://github.com/Medium/medium-api-docs/pull/70
