### ISSUE TITLE
Subtitle in post

### ISSUE THREAD

**Issue by MarcinMoskala** [Medium/medium-api-docs#124]
How do I set subtitle when I publish a post? Because it is empty by default when I publish using API

**Comment by MediumEng** [comment]
Related to this note about the title

> Note that this title is used for SEO and when rendering the post as a listing, but will not appear in the actual post—for that, the title must be specified in the content field as well. Titles longer than 100 characters will be ignored. In that case, a title will be synthesized from the first content in the post when it is published.

The subtitle should be specified as part the content field. (e.g. an `<h2>` under the `<h1>` for the title)
