### ISSUE TITLE
Processing Rmd files fails with medium_create_post_from_Rmd

### ISSUE THREAD

**Issue by aousabdo** [Medium/medium-api-docs#126]
Thank you for this nice package. 

I have a problem with the medium_create_post_from_Rmd function. When I simply knit my Rmd scripts they run fine, both as r notebooks and as Rmarkdown documents. When I invoke the medium_create_post_from_Rmd command I tend to always get errors if the Rmd document I am trying to process contains any R script. I did look at the function itself (medium_create_post_from_Rmd) and what is puzzling is that if I run the contents of this function line by line on my Rmd file things run smoothly with no errors. An example of an Rmd file I am trying to run can be found here: 

http://rpubs.com/aousabdo/crypto_2

When I use the medium_create_post on the html I generate locally from the Rmd file my post will be missing the tables and figures!

**Comment by MediumEng** [comment]
Please email yourfriends@medium.com for support. If you provide them with an explanation of what you are trying to do and the specific error you are getting, it will help them assist you!
