### ISSUE TITLE
grant_type was invalid

### ISSUE THREAD

**Issue by lucaspasquier** [Medium/medium-api-docs#130]
Hi there,

I'm trying to authenticate my app on Medium API, so I can fetch some data.

I followed all the steps in:
https://github.com/Medium/medium-api-docs

And when I recieve the "code", I try to do another post on the API and I got this error:

HTTP 400
{"errors":[{"message":"grant_type was invalid.","code":6021}]}

This is my request:

HEADER
"Content-Type: application/x-www-form-urlencoded",
"Accept: application/json",
"Accept-Charset: utf-8"

POST
https://api.medium.com/v1/tokens?code=dbc2ede843b6&client_id=XXXXXXXXXXXX&client_secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fwww.cesar.org.br

Some one could help me figure it out what am I doing wrong?

**Comment by pigrov** [comment]
I have the same mistake, have you solved it?

**Comment by pigrov** [comment]
Hi
Thank you very much for your help. Everything is now all right for me
