### ISSUE TITLE
Querying for Data from Medium

### ISSUE THREAD

**Issue by Six-wars** [Medium/medium-api-docs#131]
Hi There,
I wanted to do some querying of medium articles not in any particular order, main interest being in getting an author's name, number of claps, read time, date published and the title for a data science related post mainly being maybe I could deduce articles with a lot of claps tend to have a read time of between this and that and so on. I also post articles on Medium too. I know there's articles that need a subscription to read so if querying them for this violates some terms I'd be ok with the free articles.
The rss feed though doesn't have the claps at least which is the bench mark of how popular an article might be, I've seen you'd recommend against parsing the site with parsers so would like to know if it's doable.

**Comment by JReinhold** [comment]
I would very much like to see this also. 👍 

It is somewhat possible to query this data for you own published articles.
If you visit https://medium.com/me/stats?format=json it will give you those stats for your own posts.

However this cannot be done programmatically unfortunately, as the request relies on session cookies to be set, to validate the request. I tried sending an Integration Token along with the request, but to no avail.

As we all know, the best way to keep developers from scraping your site, is to make the information easily accessible. No one LIKES to scrape sites, it's always the last resort.

**Comment by MediumEng** [comment]
There are no plans to add a read api at this time.

Please note that the private JSON API described above is unsupported (and using it is technically against the terms of service)
