### ISSUE TITLE
Unexpected field (scope) specified

### ISSUE THREAD

**Issue by tobiastom** [Medium/medium-api-docs#132]
I'm trying to send an refresh token request to the https://medium.com/v1/tokens endpoint, but I do get the following response from the API:

```
{"errors":[{"message":"Unexpected field (scope) specified","code":6007}]}
```

As the request for the access token works as expected I would expect the refresh token request to work the same way?

**Comment by MediumEng** [comment]
Please email yourfriends@medium.com for support using the API
