### ISSUE TITLE
API to access stats data

### ISSUE THREAD

**Issue by ksimir** [Medium/medium-api-docs#134]
Similar request to https://github.com/Medium/medium-api-docs/issues/82 that has been closed a year ago.

Medium platform is really great but the stats platform lacks of flexibility. In order to do my own analytics, I would like to export my stats data accessing to it through an API. I basically want to export the stats data into my datawarehouse in an automated way.

Since the day Medium stopped supporting Google Analytics, we need alternate and more flexible way to get access to our stats data in an automated way. Do you have any plan to offer such API?

Thanks!

**Comment by bits31** [comment]
![download](https://user-images.githubusercontent.com/34608651/44294971-710dd880-a2a0-11e8-8b0a-b6ffe13b41f6.png)

**Comment by MediumEng** [comment]
There are no plans to support this.
