### ISSUE TITLE
Ulysses to Medium: posting only text

### ISSUE THREAD

**Issue by VibraniumDragon** [Medium/medium-api-docs#135]
When I post to Medium from Ulysses only text shows up on my draft. I have multiple pictures but none of them show. I have reached out to the Ulysses team and they told me to contact Medium who then sent me here.

**Comment by eveningkid** [comment]
There is a way to send more than text to Medium (their API lets you upload pictures).

So this is definitely something that can be improved on Ulysses' side. They have all the tools to make that happen, it would just take them some more development time! :)

**Comment by VibraniumDragon** [comment]
I got with the Ulysses teams and they posted my article with pictures as a test. I cannot seem to do it though.

**Comment by MediumEng** [comment]
We cannot provide support for 3rd party apps here. Please email yourfriends@medium.com if you believe there is an issue with Medium or the API. It will help if you can give them the error message or a link to one of the posts that failed.
