### ISSUE TITLE
search for posts and retrieve them? based on category?!

### ISSUE THREAD

**Issue by mohamedelephant** [Medium/medium-api-docs#136]
Hi!
I'm looking into the documentation bbut I couldn't find a way to use Medium API to get a search method. Ex: I want to search for latest articles for AI or let's say Technology. 

Is it an option in the API or not? if not what should I do for that? I'm not trying to create a Medium client. This feature will be a huge advance in the system I'm working on. 

Thanks.

**Comment by MediumEng** [comment]
This is not supported and there are no plans for this currently.
