### ISSUE TITLE
Medium needs to supply an API call for getting user stats

### ISSUE THREAD

**Issue by Dataprimes** [Medium/medium-api-docs#138]
As someone that works with data for customers, deriving insights, building dashboard, and data warehouses - one of the critical things that is needed as we incorporate medium into marketing platforms for customers. Medium is a great network / platform - and in order to complete out value, showing stats / insights from medium is critical actually now!

However there is not clear "documented" way of getting an approved user stats. As we move into supporting multiple persona's and company marketing needs, this is really a show stopper for increasing the use of medium at times. If we could easily allow of authorization of medium accounts to allow for pulling of their user stats - then this would open up a great window into critical insights. Allowing us to enable end-to-end marketing insights for those customers that use medium.

This was closed some 2 years ago actually here: https://github.com/Medium/medium-api-docs/issues/82

Is there a reason this would not be something medium would want to enable? It could really drive more people to using medium and also incorporate medium, more and more into overall content and inbound marketing platforms for customers, brands, etc. 

+1000 claps lol - if we can get this in place?

**Comment by MediumEng** [comment]
There are no plans to build a stats API
