### ISSUE TITLE
Can you get your own publications trough Self-issued access tokens?

### ISSUE THREAD

**Issue by Eviltoastey** [Medium/medium-api-docs#139]
Hey!

I don't see any possibility to get my own publications trough this API with a Self-issued access token.
I can get my own account info but I didn't succeed in getting all of my publications trough the API. Does anybody know if this is possible and if so trough which url?

Thanks!

**Comment by MediumEng** [comment]
Self-issued tokens do not have the `listPublications` scope needed for this. See: https://github.com/Medium/medium-api-docs/#22-self-issued-access-tokens
