### ISSUE TITLE
There is going to be a way to retrieve medium analytics data or inline js to medium posts?

### ISSUE THREAD

**Issue by Rolilink** [Medium/medium-api-docs#16]
I am looking for a way to create a basic analytics platform for my medium blog

**Comment by majelbstoat** [comment]
There is no facility to do this at the moment, and no current plans to offer it.

**Comment by wetzler** [comment]
Hi there - we have customers who are very interested in their medium analytics data. is there anyone I can chat with at Medium about this?

**Comment by quentin7b** [comment]
I know the issue is closed. But, if by **analytics data** you mean the data that can be found in the [Stats page](https://medium.com/me/stats) then an *API* would be great !
