### ISSUE TITLE
Post link from Instagram doesn't show the image, only description

### ISSUE THREAD

**Issue by henriquehirako** [Medium/medium-api-docs#18]
When send a link from an image on 'content' parameter, the post shows only the description of the image but without the image.
However if the same link is posted via medium platform, it works properly.

Tested links from: Instagram, Flickr and Imgur

ps: Instagram's videos works properly

**Comment by haruanm** [comment]
Same problem here =/

**Comment by ivanneto** [comment]
Same issue here  :(

**Comment by majelbstoat** [comment]
Can you paste a snippet of HTML/Markdown, let us know the expected result, and the actual result, thanks.

**Comment by henriquehirako** [comment]
Sorry for late response. I made some posts in my account to demonstrate the expected result and the actual result. Basically when I post a link through api, the post shows only the description of the image.

Starting with **Instagram**
Expected:
https://medium.com/@henriquehirako/instagram-test-through-medium-8f4c178b7b96
Result:
https://medium.com/@henriquehirako/instagram-test-through-api-e209aac54a4b
Html posted via api (basically links):
```<div class="graf-after--h3">https://www.instagram.com/p/vgw1ygg5hi/?taken-by=getblogo</div><figure class="graf--figure graf--iframe graf-after--mixtapeEmbed graf--last">https://www.instagram.com/p/BAuKUMUSH6-/?taken-by=hardwell</figure>```

**Flickr**
Expected:
https://medium.com/@henriquehirako/flickr-through-medium-eab5ddaf0df
Result:
https://medium.com/@henriquehirako/flickr-through-api-91c3dc0d4426
HTML:
```<div class="graf-after--h3">https://www.flickr.com/photos/profreiniche/24377146171/in/pool-best100only/</div>```

**Imgur**
Expected:
https://medium.com/@henriquehirako/imgur-through-medium-d07f59be46c6
Result:
https://medium.com/@henriquehirako/imgur-through-api-9b2a45a6228
HTML:
```<div class="graf-after--h3">http://imgur.com/gallery/0Zxmke4</div>```

Thanks

**Comment by huckphin** [comment]
Thank you for the report. We will start working on this on our end.

**Comment by huckphin** [comment]
@henriquehirako: Sorry for the insane delay. Busy times. From the test bed that we have internally, this is looking good on our end now. May I ask you to take a look and try again. If you still see a problem, can I ask you to reopen and provide more details on the actually HTTP request you are making to our API including headers?

Thanks!
