### ISSUE TITLE
Value of rel="canonical" being changed in the DOM

### ISSUE THREAD

**Issue by adactio** [Medium/medium-api-docs#19]
If a new post is created on Medium using the API, and a value is provided for the canonicalUrl parameter, this value shows up in the *source* of the document on Medium (i.e. what you see when you "view source") in the value of the <code>rel</code> attribute on a <code>link</code> element in the <code>head</code> of the document.

However, this value is then changed. If you "inspect element", that DOM node now has the Medium URL instead of the correct value.

So there must be some JavaScript somewhere on Medium that's updating this value.

(I realise that technically this issue is for the Medium site rather than the Medium API, but as it relates to the canonicalUrl parameter, I thought it best to post it here)

<https://medium.com/@AaronGustafson/i-discovered-something-peculiar-in-medium-s-implementation-though-in-the-source-the-canonical-url-ba041ebdf437>

**Comment by adactio** [comment]
*tap* *tap*

**Comment by adactio** [comment]
Tumbleweeds.

Is there somewhere else where I should be filing this issue?

**Comment by kylehg** [comment]
Hey @adactio, sorry for the lack of a faster response! I think we're still working out the process fow how we keep up with issues filed here.

This is definitely a bug on Medium, so I'm filing it on our end and will keep you posted about the fix. Thanks for bringing to our attention!

**Comment by adactio** [comment]
Thanks, Kyle!

**Comment by LandonSchropp** [comment]
This is an issue for me as well. I'd really like to see this resolved so I don't get dinged by Google for hosting the same content on my blog that I have on Medium.

**Comment by mikkot** [comment]
Hey all - this issue has been resolved! There was a bit of confusion between clients and server around which URL parameters to use for which purpose, but that was sorted out.

**Comment by adactio** [comment]
Fantastic! Thank you, @mikkot.

**Comment by LandonSchropp** [comment]
Thanks @mikkot!

**Comment by mikkot** [comment]
:bow:
