### ISSUE TITLE
Feature Request: Likes

### ISSUE THREAD

**Issue by custa1200** [Medium/medium-api-docs#24]
I'd like to be able to retun a list of things I have liked which I think is quite different to the publications view.

**Comment by bertramakers** [comment]
Agreed, I think this would be a useful addition. I was thinking about creating a script that posted a daily digest of the likes of various of our employees (opt-in) in HipChat (Slack would work too of course), but all "likes" data seems to be missing.

**Comment by custa1200** [comment]
My use case is on my personal site I would like to be able to have a list of things I have recently liked for for people to get a feel for what I am reading and enjoying or finding useful.

**Comment by majelbstoat** [comment]
There's currently no facility for doing this through the API, but you can make use of an IFTTT trigger on the Medium channel.
