### ISSUE TITLE
API Rate Limit

### ISSUE THREAD

**Issue by srccd** [Medium/medium-api-docs#28]
I may have borked something, but I hit the rate limit with a self-issued token after about 15 "posts" (create post) calls and a few "me" calls. So probably under 20 calls in total using the Python SDK.

"User ... has reached the rate limit for publishing today"

In reference to https://github.com/Medium/medium-api-docs/issues/10, maybe that "dynamic limit" is very strict on new-ish accounts, but 15 is painful. I know it's not a documented limit, but is it really that tight?

In addition, is the limit refreshed every 24 hours or at 12am each day?

Edit: Tried again today (Dec 18) and found that I could only complete 10 "posts" (create) calls before I got the rate limit error. Sure would like a way to get a temporary exclusion.

**Comment by majelbstoat** [comment]
We're working on better rate-limiting semantics, but are being overly conservative at the moment to avoid abuse.

**Comment by huckphin** [comment]
We now have a way to increase the rate-limiting on a publication. We will remove the restriction on a case-by-case basis. Please reach out to us at yourfriends@medium.com if you require an increase in the rate limit for your publication. Please provide:

1. the name and URL of your publication
2. the maximum expected published posts you need in a 24-hour period
3. the length of time that you require a rate limit increase

Once we have those three items we need, we will remove the restriction on your publication, and notify you that the process is complete.

At this time, we do not have any plans to increase the daily publishing limit across the entire platform.
