### ISSUE TITLE
Image with link

### ISSUE THREAD

**Issue by srccd** [Medium/medium-api-docs#29]
When importing an image with a link attached to it, the link gets dropped.

**Comment by majelbstoat** [comment]
Can you give more information, please. For example, some HTML or Markdown, what you expect, and what is actually created.

**Comment by huckphin** [comment]
Needs more information.

**Comment by srccd** [comment]
Unfortunately, I moved on due to small issues such as this. With that, I apologize for not responding until now.  I'm circling back and noticed that this issue is still ongoing. In my case, I'm trying to import a wordpress XML, and it contains something such as:
`<a href="http://www.test.com/image_big.jpg"><img class="alignnone" src="http://test.com/image.jpg" alt="Thumb." width="225" height="300" /></a>`

The thumbnail image appears fine, but it loses the anchor/link. Even if the link is to a web page.

It appears such links are ignored to coincide with Medium's design, but the automatic loss of the link is concerning.
