### ISSUE TITLE
GET /posts - retrieve a list of user posts?

### ISSUE THREAD

**Issue by dylan-baskind** [Medium/medium-api-docs#30]
Hey there,

Am I missing something, or is there currently no way to retrieve a list of the stories a user has written?

(Understand you guys are focussing on the publish-to-Medium aspect of the API for now, but getting a list of stories would be ace!)

**Comment by erinc** [comment]
I'm surprised with lack of /posts as well. It seems like there's no way to access user posts.

**Comment by acao** [comment]
I imagine that they didn't provide this because there are already RSS feeds, however the RSS feeds do not provide the up-to-date list that an API would provide. It's also possible that this is a walled garden issue - they probably don't want readers to use anything but their own browser or mobile clients for reading articles.

**Comment by nicks** [comment]
ya, there's an RSS feed, for example,
https://medium.com/feed/@ev

**Comment by pburtchaell** [comment]
Is there no future consideration in providing a `GET /posts`? While it is nice the RSS feed exists, I can't effectively limit the number of posts returned and it is a _pain_ to parse. My use case is fetching my latest posts from Medium so I can list them on my personal website. I really don't care about the body of the website —I only want titles, descriptions, meta data (like date posted) and links. I understand if it is a walled garden issue as @acao mentioned, but I think at least providing some basic information on posts is reasonable.

**Comment by erinc** [comment]
This is **undocumented** but should work:

Make a GET request to `https://medium.com/@ev/latest` with `Accept: application/json` header. You can pass `count` parameter to limit the posts. Much easier to parse than RSS.

**Comment by nicks** [comment]
i'm surprised you're having trouble finding a library to parse RSS? It's a pretty well-understood and well-supported standard.

**Comment by acrodrig** [comment]
@erinc:

When I try to do the undocumented call you mentioned. I get a message back that starts with:

```
])}while(1);</x>{"success":true,"payload":{ ...
```

Could you validate that it is a bug and not a problem on my side? Thanks.

**Comment by erinc** [comment]
@acrodrig it is not a bug or a problem on your side. I think the response includes that code to prevent [JSON Hijacking](http://stackoverflow.com/questions/2669690/why-does-google-prepend-while1-to-their-json-responses). You can strip that part in your server side before parsing it as a json.

**Comment by elwayman02** [comment]
Sad to see this issue closed... This is pretty much a must-have for working with the API. I want to move my site's blog from Tumblr to Medium, but without having a way to easily query public posts (rss feed obviously doesn't cut it),  that's pretty much a non-starter. Really sad that Tumblr seems to be the superior product here... :/

**Comment by j3ddesign** [comment]
I ran into this issue today and ended up writing a small graphql wrapper around the undocumented json response mentioned above.
If anybody is interested - you can check it out at https://github.com/j3ddesign/medium-graphql
Still lots I need to do for my own project, but hopefully that'll help somebody :)

**Comment by RickStrahl** [comment]
This is seems pretty lame to have an API that doesn't allow you to return POSTs? What kind of API lets you put data in and not get it back out via the same API?

Utter #fail

**Comment by markfasel** [comment]
Hi there, I have built a basic function using AWS Lambda and AWS API Gateway if anyone is interested. A detailed explanation is found on [this blog post here](https://medium.com/@markfasel/building-a-basic-web-service-to-display-your-medium-blog-posts-on-your-website-using-aws-api-48597b1771c5) and the repository for the the Lambda function built with Node.js is found here [https://github.com/markfasel/medium-nodejs-lambda](url)

**Comment by enginebai** [comment]
Hi, I've built a [PyMedium - Unofficial Medium API](https://github.com/enginebai/PyMedium) to provide a easier way to access information from Medium.

https://github.com/enginebai/PyMedium
Star and contribution are welcome.

**Comment by Crityk** [comment]
Hi @enginebai can I get a list of publication posts by using PyMedium? I need to show recent first three on my website for any specific publications. Kindly let me now.

Thanls

**Comment by enginebai** [comment]
@Crityk Yes, just call `/{publication_name}/posts?n=3`, and you will get the latest 3 posts from `publication_name`.

**Comment by Crityk** [comment]
like this https://medium.com/crityk/posts?n=3? but its not working.

**Comment by Crityk** [comment]
I am able to get post using RSS feed https://medium.com/feed/crityk but can you please correct above url link? would like to use that instead. thanks

**Comment by Crityk** [comment]
@enginebai would appreciate if you answer soon as stuck on this for days now.

**Comment by newhouse** [comment]
Hi @Crityk and @enginebai 

PyMedium looks like a nice tool to help with some of the (currently) missing pieces of Medium's official API - nice work and I think I'll be able to use it myself!

However, in an effort to keep this thread (and this repo's board in general) focused on Medium.com's official API capabilities, could you discuss PyMedium questions/issues over on the [PyMedium Issues](https://github.com/enginebai/PyMedium/issues) area? Thanks!

**Comment by enginebai** [comment]
@newhouse Thanks, let's discuss in [PyMedium issues](https://github.com/enginebai/PyMedium/issues), @Crityk you can open a issue to discuss.

**Comment by Crityk** [comment]
ok thanks guys

**Comment by evenchange4** [comment]
FYI, here is another demo microservice for fetching posts with GraphQL: 
https://github.com/evenchange4/micro-medium-api

**Comment by CrySensai** [comment]
hello,

is there any php solution?

**Comment by michaeldever** [comment]
This has been an issue for 2 years, I wonder if there's a resolution in the pipeline. It's quite silly to have to implement another service to pull in posts and then pass them on to a client, when the client should be able to do that itself.

**Comment by jsparanoguy** [comment]
@evenchange4 i forked your repo probably gonna add some stuff to retrieve more data but i have to say its really awsome !!

**Comment by DhirajBelure** [comment]
Below code fetch the stories of user 

*************************************************code**************************************************
 $ch = curl_init();

    // set URL and other appropriate options
    curl_setopt($ch, CURLOPT_URL, "https://medium.com/feed/@ev");
    curl_setopt($ch, CURLOPT_HEADER, 0);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

    // grab URL and pass it to the browser
    $xml = curl_exec($ch);
    $feeds = simplexml_load_string($xml);
     $i = 0;
    foreach ($feeds->channel->item as $media) {

               echo $item->description;

              echo (string)$media->title;
              echo (string)$media->children('http://purl.org/rss/1.0/modules/content/')->encoded; 
              echo (string)$media->link;
               $i++;

    }           
******************************************************end*************************************************
