### ISSUE TITLE
Feature Request: Allow access to notifications

### ISSUE THREAD

**Issue by hasit** [Medium/medium-api-docs#32]
I would be interested in getting authenticated user's notifications through the api. Something like [Github's Activity](https://developer.github.com/v3/activity/).

I envision this API exposing user's activity such as
- followers for user
- recommends on post
- response to posts

Are there any plans for this feature?

**Comment by majelbstoat** [comment]
There are currently no plans for this I'm afraid, and given that, I'm going to close this for now. We will keep it in mind as we expand the API, but there's not much value in having the issue stay open at the moment.
