### ISSUE TITLE
Post preview issue

### ISSUE THREAD

**Issue by jescalan** [Medium/medium-api-docs#33]
I recently started using an editor that uses Medium's publishing API for drafts and have been thoroughly enjoying it. However, since switching over I have noticed a strange issue in how post previews are rendered, showing little paragraph signs rather than simply using my h2 as the post summary.

You can clearly see the issue (and the difference between the new and old posts) here: https://medium.com/pragmatic-life

Thanks so much for all your good work on such a lovely publishing platform, and please let me know if there's any ways I can further help with this issue or anything else :grinning:

**Comment by huckphin** [comment]
Thank you for the report. We will start working on fixing this.

**Comment by huckphin** [comment]
It is currently not prioritized, but still have this as something that we need to do.

**Comment by jescalan** [comment]
Would be awesome if this was worked out! Thanks for your good work guys
