### ISSUE TITLE
API endpoint for a list of top stories

### ISSUE THREAD

**Issue by samuelclay** [Medium/medium-api-docs#36]
Hi Medium, I've created a physical remote control for Medium (among other things), allowing people to read Medium from a new full screen reader application for Mac. I want an API endpoint that provides a list of the authenticated user's top stories as well as the ranked stories from the homepage. I just need the URL, although title, author, and any other meta data would be helpful.

Here's a photo of how it will look:

![2016-01-13 16 16 21](https://cloud.githubusercontent.com/assets/44229/12365410/8b1444b8-bb89-11e5-81e5-16148df720dc.jpg)

**Comment by huckphin** [comment]
Thank you for the suggestion! At this time, we do not have this planned on our roadmap. I will take take this suggestion to the next product planning sessions.

**Comment by Menda** [comment]
I don't know if this is exactly what I thought, but I'd like to include in my page a list of the last stories written from a publication, just providing author, title, an image and a URL, so users can click to it and get redirected to the story in Medium. Maybe are we talking about the same?

**Comment by samuelclay** [comment]
Now that @julien51 is on board at Medium, can we push this up? I'm planning to launch my campaign in September and I'd love to have native Medium support.

**Comment by geordidearns** [comment]
+1
