### ISSUE TITLE
API support for retrieving  user's highlighted texts?

### ISSUE THREAD

**Issue by yask123** [Medium/medium-api-docs#38]
Eg: this, https://medium.com/@yask123/highlights

**Comment by huckphin** [comment]
Thank you for the suggestion! This is not currently on our roadmap. At the next product planning session, we will take this into consideration. Thank you again for the suggestion.

**Comment by fabianmu** [comment]
I'd love to see this, too. +1

**Comment by saiichihashimoto** [comment]
This would be AWESOME. So many fun things can come of this.

**Comment by jnv** [comment]
Yes please. I would like to work on an interop with other tools like Hypothes.is, Instapaper or Genius.

**Comment by dariodaprile** [comment]
+1

**Comment by kylehg** [comment]
Sorry, we're not sure how this got reopened — we'll keep this feedback in mind, but highlights are not currently on the roadmap.
