### ISSUE TITLE
Overriding publishedAt?

### ISSUE THREAD

**Issue by mspanc** [Medium/medium-api-docs#43]
Hello,

I would like to migrate old blog into medium, but I would like to maintain the original publishing date, is there any way to do this?

**Comment by huckphin** [comment]
Hello @mspanc: If you are using the API to migrate your content, you can set a date in the past for the `publishedAt` field, and this will become the creation date of the post in Medium.

If your content is stored in Wordpress, and if you use the Medium Wordpress Plugin, the post creation date will use this feature to retain the publish date of all of your blog posts.
