### ISSUE TITLE
API request to post blog in markdown

### ISSUE THREAD

**Issue by yask123** [Medium/medium-api-docs#44]
Many people have been blogging before medium existed.
Most people have been using things (like Jekyll, Octopress..or Ghost) hosted on their personal website.

Now medium has become a new cool place, which does makes it a lot easier to share content to the world.

However, people still don't wish to abandon their old blogs and end up posting new content manually in both places by copying and pasting.

I wish there was an API , so we could integrate automatically posting markdown content on Medium ?

And others are facing the same problem.
Eg: 
* https://medium.com/@karan/twitter-years-after-the-alphabet-acquisition-3f5b5b168fb5
* https://goel.io/twitter-alphabet/

**Comment by huckphin** [comment]
I agree with you. Medium is new, and blogging has been around for awhile. We want to make it easy for others to share their content.

We currently have a way to post content via [Markdown](https://github.com/Medium/medium-api-docs#creating-a-post), but it is a little buried in the docs! You need to specify the contentFormat as either "HTML" or "markdown", and from there, you will be able to post content from Markdown. Let us know if you are having any issues with this.

In regards to simple integrations with other platforms, we currently have a [WordPress plugin](https://wordpress.org/plugins/medium/) that you can install to cross post on Medium when you publish on WordPress. It adds a new menu that will allow you to post on Medium with details such as License, Public/Draft/Unlisted, the option to notify your Medium followers, and the option to add your post to any publication that you own on Medium.

**Comment by BlackGuyCoding** [comment]
@huckphin any chance you guys are working on other plugins? I use Ghost blog and want to post n Medium as well.

**Comment by huckphin** [comment]
We don't have any plans for more plugins right now, but it is something that we would be interested in pursuing for other platforms besides just WordPress.
