### ISSUE TITLE
How to use it in non-browser applications?

### ISSUE THREAD

**Issue by devkhan** [Medium/medium-api-docs#45]
The steps given are for browser apps where redirection is possible, but how do we use it in non-browser apps e.g. native mobile, embedded apps, desktop apps, etc. ?

**Comment by huckphin** [comment]
We do offer SDKs for our API that you can use in various languages. We currently have SDKs available for [Go](https://github.com/medium/medium-sdk-go), [Node.js](https://github.com/medium/medium-sdk-nodejs), [Swift](https://github.com/medium/medium-sdk-swift), and [Python](https://github.com/medium/medium-sdk-python) which are officially supported. We currently have one (unsupported) SDK in [Haskell](https://github.com/timmytofu/medium-sdk-haskell) from @timmytofu.

If those languages do not work for you, then you can still use our native HTTP library to write something in the language of your choice, but it might be more challenging to do so.

Hope this helps.

**Comment by devkhan** [comment]
Thanks for replying but that's not the issue, I wanted to use the API in a a desktop app. Anyway. I have figured that the only way is by using integration(self-issued) tokens.

**Comment by halonsoluis** [comment]
Hi @huckphin, What about your Swift API? It appears not to be public

**Comment by huckphin** [comment]
Hi @halonsoluis: Oops, I might have let that one slip too soon. I did not yet realize that it was not public. It is in the early alpha stages, but we have no idea when the release date will be for the Swift SDK, but we are actively working it in regards to all of our API/SDK priorities.
