### ISSUE TITLE
Redirecting to the authorization URL results in HTTP 400

### ISSUE THREAD

**Issue by JaffParker** [Medium/medium-api-docs#47]
I'm trying to implement sign up with Medium on my site, but I fail at the very first step. The URL looks like this:
```
https://medium.com/m/oauth/authorize
    ?response_type=code
    &client_id=8893219e1161
    &state=0kWPLebp4UjK1Nz9
    &scope=basicProfile,listPublications
    &redirect_uri=https://koodzo.dev
```

I checked many times, all the parameters are there and are correct. However, I keep getting error 400. Normally, it would mean I messed up with arguments, but it doesn't seem to be the case. What could be the problem here?

**Comment by JaffParker** [comment]
I'm an idiot, I messed up the allowed redirect URLs, that's all.

**Comment by remirobert** [comment]
@JaffParker I have the same issue. Can you tell how you deal with that ?
I want to use that in my iOS app. So I don't understand what should be the redirect URL, because on the dev platform the right format is **http://**, but in my app I need something like : **myApp://**

Thanks in advance.

**Comment by JaffParker** [comment]
@remirobert I haven't ever developed a mobile app, so I don't really know how to implement it. I guess it's similar to web, you can look at any other OAuth2 provider such as Facebook, for examples. They all follow the OAuth standard precisely.

**Comment by polaski** [comment]
I can confirm this doesn't work on mine either. Medium doesn't allow you to enter an app url scheme for APIs therefore I can't use Oauth on my iOS app. Is this intended? (In which case, what's the point of an API?)

**Comment by timyaodpc** [comment]
Make sure that callback url in your request is in your Medium app `Callback URLs`.  Otherwise it will give you a 400 response page.
