### ISSUE TITLE
[Request] Add CRUD methods for posts

### ISSUE THREAD

**Issue by rogervila** [Medium/medium-api-docs#52]
Hello, 
I have seen in the docs that there is an endpoint for creating posts, but there are no methods for creating and editing posts.

**Comment by simongfxu** [comment]
+1 for post modification

**Comment by benmedium** [comment]
Hello!

This is something that's on our radar, but isn't in place right now. I'd love to hear about the kinds of applications you'd like to build with this API.

**Comment by simongfxu** [comment]
I am building a client tool to sync posts to several platforms.
The purpose is to write in markdown and to publish everywhere.
https://github.com/simongfxu/violet

**Comment by benmedium** [comment]
Neat!

I'm sorry we don't have this functionality right now. However, hopefully the ability to publish will allow you to get started.

**Comment by Chandler** [comment]
@benmedium It would be great to be able to keep my source of truth for my post content elsewhere (say in github). An update method would allow me to build a hook to update my medium post automatically when I push new revisions to github.

**Comment by tjmonsi** [comment]
When will the update mechanism be out?

**Comment by theranger** [comment]
As a response to #22 I do not expect any progress on it soon. It's a pity that putting all the development power of other minor and more or less irrelevant enhancements, the whole purpose for an API is defeated by skipping this basic functionality.

I'm sure many of us, including me, are not even considering Medium as a publishing platform before update/delete functionality is implemented and are rather sticking to a Wordpress or any other blogging system instead.

**Comment by enginebai** [comment]
+1, I'd like to create a markdown transformation tools for post so that I can sync my post to every platform I owned, but found that official API does not support post get API.

**Comment by 1999** [comment]
For me just PUT/PATCH method support for updating posts would be enough to sync between github markdown posts and medium publications.

Smth like this:
```
curl \
	-H "Content-Type: application/json" \
	-H "Accept: application/json" \
	-H "Accept-Charset: utf-8" \
	-H "Authorization: Bearer ..." \
	-d '{"title":"Liverpool FC - new title"}' \
	-X PUT \
	https://api.medium.com/v1/publications/publication_id/posts/post_id
```

**Comment by RickStrahl** [comment]
+1 here. I'm author of Markdown Editor with blog publishing features([Markdown Monster](https://markdownmonster.west-wind.com)) and I have many, many requests for integration with Medium. We currently support MetaWeblog API and WordPress. 

But given this limitation building an integration interface is just going to bring us a shitload of support requests as to why users can't update their posts.

No offense guys, but this is pretty lame. It can't be that difficult to provide an update mechanism to a post, and the ability to get a list of posts.

Heck the existing POST API running a PUT with an existing ID would be enough.

Puzzled why there's so much resistance to this.

**Comment by enginebai** [comment]
Hi, I've built [PyMedium - Unofficial Medium API](https://github.com/enginebai/PyMedium) to provide developers a easier way to access data from Medium.

Star and contribution are welcome.

**Comment by acloudburo** [comment]
I would like to connect my Evernote PublishingBot to Medium but would require Update and Delete to get a decent user experience. Could live without "Delete" but "Update" is really required. Agree with @RickStrahl put a PUT request shouldn't be too much of effort. https://publishingbot.cloudburo.net/

**Comment by grazz** [comment]
Any news on this? Was this implemented already? I can't find anything in the documentation.
I know nothing about the internals, but it doesn't sound too absurd to provide an unique id for the post and allow to re-post(replace) them.
Is there a reason it's not implemented?

**Comment by mchristen** [comment]
Any update on this?

I just want the ability to update the canonicalUrl of posts that are already published....

Seems like this is basic functionality for any RESTful API...

**Comment by cjmielke** [comment]
Same - trying to update the canonical URL. The fact that I can't is really driving me away from the platform.

**Comment by MediumEng** [comment]
Unfortunately there are currently no plans for building enhancements to the API.
