### ISSUE TITLE
Specifying image layouts when posting through the API

### ISSUE THREAD

**Issue by gesteves** [Medium/medium-api-docs#57]
When posting a story through the API, is there a way to specify how images in the content are laid out? Right now they seem to default to this:

![screen shot 2016-06-15 at 8 51 41 pm](https://cloud.githubusercontent.com/assets/6379/16102190/37ae5f32-333b-11e6-8f4f-e5ad14aa50a8.png)

Is there a way to make an image full-width, for example, through the API? (Perhaps by adding a class or data attribute to the image tag?)

**Comment by benmedium** [comment]
Unfortunately not right now, but that's a great feature request.

**Comment by MediumEng** [comment]
Enhancements to the API are not planned at this time
