### ISSUE TITLE
Set date of post

### ISSUE THREAD

**Issue by balupton** [Medium/medium-api-docs#6]
I'd like to use the API to mass import all my old blog posts from various sources — however I do not want them to be sorted and shown as if they are new content, they are not, more so they are years old.

I have no idea how to achieve such a thing with medium, does medium not care about accuracy of post dates?

**Comment by tobiastom** [comment]
I would also like to use this.

**Comment by majelbstoat** [comment]
There is currently no support in the API for backdating or future scheduling of posts. It is planned for the future, but I have no specific timeframe to share with you yet.

**Comment by luisrudge** [comment]
thiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiis please :) I'm building a feed importer for medium and it would be awesome to set the date of the post.
Thanks!

**Comment by luisrudge** [comment]
BTW, I just pushed the code to import a rss feed [here](https://github.com/luisrudge/medium-import-feed)

**Comment by srccd** [comment]
Sure would love this to be added sooner rather than later. Many don't like to swap publishing services if they can't carry their old content to the new platform. Personally, I'm one of those who would prefer to import older content with a timestamp. So please give us write permissions to publishedAt.

I understand the concerns with this causing a resource utilization spike, so maybe let us pay a fee for access for a certain duration.

**Comment by dgrobinson** [comment]
+1 on this. We've got a lot of strong content over at EqualFuture.us and I'd love to be able to import it to Medium. But we would need to be able to preserve the correct (original) publication dates. We would not mind if some coding were required in order to accomplish this.

**Comment by majelbstoat** [comment]
It's currently undocumented, but this is now supported. You may now set a `publishedAt` date, in full ISO8601 format. For example: `2004-02-12T15:19:21+00:00`

If specified, the publishedAt date must be in the past, to avoid any misunderstanding that posts can be scheduled for the future.

If you are importing a lot of posts, we strongly suggest you also set the new `notifyFollowers` flag to `false`. This will avoid spamming followers with push notifications and feed entries.

**Comment by adriangodong** [comment]
@majelbstoat Can we make publishedAt data format the same as the output, i.e. UNIX timestamp?

**Comment by majelbstoat** [comment]
In all likelihood a future update (with plenty of notice, and probably a version bump) will change the output to the same ISO format. We prefer this for meaningfully capturing dates in the far past. Sorry for the inconsistency, that's my fault.

**Comment by luisrudge** [comment]
@majelbstoat can we change a published date for a post? I now have imported all my posts using my [custom rss feed importer](https://github.com/luisrudge/medium-import-feed), but now all the dates are wrong and I had to add some notice on the top of the article saying that the post was originally written XXXX days ago

**Comment by majelbstoat** [comment]
There is currently no facility for changing the post date of an existing post. We're exploring options for this in the UI, and may have something to share in the new year, but nothing solid yet.

**Comment by lutzroeder** [comment]
Add supported for publishAd to the importer. Pull request here: https://github.com/luisrudge/medium-import-feed/pull/1. Next getting blocked by the daily post limit when trying to import a feed with a few dozen posts. Medium is missing a few features (proper RSS import, modifying publish dates, traditional RSS support, remove 'XX on Medium' in the RSS title) that would make it a usable alternative to Blogger/Tumblr/WordPress. Not sure why this is not getting added faster. There is only so much attention span users will have until "Medium is great but it's unusable as a blogging tool" will become a stigma.

**Comment by huckphin** [comment]
The API now supports a `publishedAt` date, which resolves the original issue reported by @balupton. @lutzroeder: The daily post limit is overly conservative right now to avoid abuse. If you have an issue with a rate limit being too low, feel free to reach out to our Customer Support yourfriends@medium.com, and provide them with the name of the publication that you want, and the rate limiting can be removed on a per-publication basis. Please indicate how long you need the daily post limit bumped on the publication when making the request.

**Comment by tobiastom** [comment]
Thank you for adding this functionality!

**Comment by mandersondesign** [comment]
Can I get any update on this issue to update an already imported blog publish date? We are trying to move over from Hubspot, and unfortunately they don't give a full rss feed of the blogs. So I am just importing all our posts in order, in order to at least preserve publish order. but really, I would love to add the actual date it was originally published. 

Love to get any insight if this is on the horizon!

Thanks.

**Comment by sethfam** [comment]
I'm in the exact same postion as @mandersondesign.  Can someone from @Medium please provide guidance on how to backdate posts using the Medium UI, not the API?  Or should we just contact @Medium support directly and get help with manual changes.  Thx for your help!!

**Comment by peteforsyth** [comment]
+1, archiving past publications, would very much like to apply the correct date. Example: https://medium.com/@PeteForsyth/updating-mt-tabors-master-plan-f6ad7331ed6c

**Comment by olgageletina** [comment]
Is it possible to alter a publishedAt date for a post authored by someone else?

**Comment by xameeramir** [comment]
Please do this fast!
