### ISSUE TITLE
Support callback URL schemes different from http: and https:

### ISSUE THREAD

**Issue by martinpilch** [Medium/medium-api-docs#64]
Hi,
to be able to authorise and access Medium API in my iOS app I need to specify callback URL with custom URL scheme (e.g. myApp://myapp.com/callback/medium)
Is there a reason you're restricting it to http: and https: only?

Thank you

**Comment by MediumEng** [comment]
This is a very valid request, but unfortunately we are not planning on making changes or enhancements to the API in the foreseeable future.
