### ISSUE TITLE
Update Documentation to Discuss "publishedAt" in Posts

### ISSUE THREAD

**Issue by ddrum001** [Medium/medium-api-docs#66]
It would be very helpful to add to the "Posts" (i.e. section 3.3) of the documentation to note that the "publishedAt" date can be overridden as discussed in https://github.com/Medium/medium-api-docs/issues/43 and https://github.com/Medium/medium-api-docs/issues/6.

It also seems that the date must be in ISO8601 format (even though the response is in Unix Epoch time), which makes the documentation even more imperative.

**Comment by MediumEng** [comment]
Closing just for repo maintenance. Thank you for the suggestion!
