### ISSUE TITLE
Stories not appearing reverse-chron in "Latest"

### ISSUE THREAD

**Issue by designmeans** [Medium/medium-api-docs#67]
In the Bento publication homepage, under the "Latest" section, posts do not appear reverse-chronologically, by date published (as indicated by the date stamp in the post and post preview). Rather, they appear in order of when they were added to the publication, which is counter-intuitive to the reader, who sees dates out of order as in the screenshot. Julia tells me it also creates an issue for migration, because they have to always go from oldest the newest post, rather than in chunks out of order, because Medium does not sort by date published (according to the timestamp/dateline).

cc @shitijagarwal 

![screen shot 2016-08-10 at 3 01 41 pm](https://cloud.githubusercontent.com/assets/7736735/17608320/ba41e1fe-5ff9-11e6-86ba-7e9c496671f0.png)

**Comment by huckphin** [comment]
This issue was moved to Medium/medium2#39205
