### ISSUE TITLE
"publishedAt" dates not used in publication's "Latest" reverse chronological order story sort

### ISSUE THREAD

**Issue by grokify** [Medium/medium-api-docs#68]
When I publish a post using the API with `publishedAt` set to a historical date, the date is displayed properly but it's still listed "later" than more recently dated posts with an earlier post date on the publication home page. This is seen on the [publication's "Latest" story sort order](https://help.medium.com/hc/en-us/articles/215125848-Publication-layout).

Is there a way to get the story to sort by the `publishedAt` on the publication home page when set to sort by "Latest" stories?

**Comment by grokify** [comment]
More info:

The `publishedAt` date is used for the author's Latest sort order.

The date used for the publication's Latest sort order appears to be the attach date. I haven't found a way to manipulate this via the API but the publication sort order can be managed by detaching and re-attaching articles to the publication.

**Comment by MediumEng** [comment]
Thank you for the report. This is a known issue, but it is surprisingly hard to fix and due to limited resources will likely not be prioritized.
