### ISSUE TITLE
CRUD for responses

### ISSUE THREAD

**Issue by snarfed** [Medium/medium-api-docs#71]
similar to #52, but for responses on posts. even just a read only API, per post, would be great. i'm sure this has been on your radar since the beginning; just starting a place to capture discussion here.

there are obviously nontrivial spam, authenticity, and signal to noise issues. if those are blockers right now, i'd happily try out and give feedback on any limits or other techniques you might consider.

i know you all support programmatic use of your existing RSS feeds, so one incremental approach here could be RSS feeds of responses on each post.

thanks in advance!

**Comment by MediumEng** [comment]
Hi snarfed!

**Comment by MediumEng** [comment]
Thank you for the suggestion. Unfortunately there are no plans for enhancements to the API in the foreseeable future.
