### ISSUE TITLE
Get followers count

### ISSUE THREAD

**Issue by terflogag** [Medium/medium-api-docs#73]
Hi,

I'm looking for way to get Medium's profil followers. Can we get it with Medium Api ?

Thank you

**Comment by gavindinubilo** [comment]
Hey @terflogag, it's possible to get this from `https://www.medium.com/@username?format=json` or requesting the users profile page with `Accept: application/json` header, though it's a little tricky to parse the JSON, the number you're looking for is in `payload` > `references` > `SocialStats` > `{userId}` > `usersFollowedByCount`

The tricky part is the `USERIDHERE` part, you just have to grab the user id from `payload` > `user` > `userId`

**Comment by terflogag** [comment]
Work great with https://www.medium.com/@username?format=json, thank you ! :-)

**Comment by terflogag** [comment]
I can't get valid JSON format, got "while(1)" at the beginning of the response. Any idea ?

**Comment by gavindinubilo** [comment]
You have to strip that out, they add that to avoid JSON Hijacking, read more about it here https://github.com/Medium/medium-api-docs/issues/30#issuecomment-227911763 it'll be the same everytime, so before you parse the json you can just replace `])}while(1);</x>` with an empty string.

**Comment by newhouse** [comment]
This was quite useful, thanks everyone! Made a gist of the whole thing working in case anyone else comes across this:

https://gist.github.com/newhouse/843c444ddefe084ea7f01603627dbcfd
