### ISSUE TITLE
null is not an allowed domain. Our host is (api.medium.com:443

### ISSUE THREAD

**Issue by goodhyun** [Medium/medium-api-docs#77]
This might not be an issue, but I'll describe the symptom for the future reference.

`{"errors":[{"message":"null is not an allowed domain. Our host is (api.medium.com:443, /v1/tokens)","code":-1}]}
`

This is happening when you are requesting the API using a Fetch api on electron.
If you take a look at the request headers : 

```
origin:null
port:443
```

I didn't see a way to reset the origin here, so I resorted back to the node's `https` module. 
Other API platforms didn't give us this error yet, with the same format.

**Comment by anmolvarshney1993** [comment]
Did you find any solution ?
