### ISSUE TITLE
Any plans for a stats api?

### ISSUE THREAD

**Issue by Skilgarriff** [Medium/medium-api-docs#82]
I would really love to be able to have some sort of an API that can feed me the basic stats that Medium provides. This is extremely important for me for a project that I am working on, so I would do anything that I could to potentially help with this. 

I noticed that the actual software driving the API is not open sourced. Are you open to contributions towards that API? I would love to be able to help 👍

**Comment by kylewm** [comment]
Thanks for your request, unfortunately this is not on our roadmap at this time.

**Comment by attilavago** [comment]
I think this is a valid request and should be reopened. It would be great if people could hook into their basic stats from their website, etc, something like total number of reads in a month/year/forever.

**Comment by mdavarynejad** [comment]
I can see that many Medium users need to have access to the stats of their posts, the number of reads, etc. Some users are hesitating to move to Medium just because they do not have full access to their data.

**Comment by andene** [comment]
+1

**Comment by gavrilobozovic** [comment]
I'd second that. Medium recently dropped custom domain names, so I imagine they want to bring people on their platform instead of driving traffic elsewhere?

If so, please let us properly analyze engagement on your platform!!

**Comment by javedsha** [comment]
+ 1

**Comment by nathanpeck** [comment]
+1 Would like to see an API for fetching the stats for my own posts, and posts on my publication, even if this is a paid tier of API access.

**Comment by bramsdenteuling** [comment]
+1

**Comment by mbrn** [comment]
+1

**Comment by ksimir** [comment]
+1000 would like to export the stats data from Medium to my datawarehouse.

**Comment by MicroBenz** [comment]
+1

**Comment by fh48** [comment]
+1000. Medium is the core component of my marketing funnel which I want to fully monitor over a single dashboard.

**Comment by AyoPrez** [comment]
+1
