### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by danielllano** [Medium/medium-api-docs#83]
Hello. I'm looking for an application which I can use for creating posts and use an API for querying this post from my own app for my users. In your docs I can see that I can list user's publications but I would like to know if you support querying a specific publication retrieving its html content with a path like:

GET https://api.medium.com/v1/publications/{{publicationId}}

Thanks

**Comment by olgageletina** [comment]
+100 to this feature

**Comment by MediumEng** [comment]
There are currently no plans to support a read API
