### ISSUE TITLE
Authentication issues (using Python SDK)

### ISSUE THREAD

**Issue by olgageletina** [Medium/medium-api-docs#84]
For some reason, I am getting a 400 error trying to authenticate using the python SDK. Previously I was able to do so fine, the only difference now is an added uploadImage scope to the authorization url. Confirmed that my application_id, application_secret, and callback URL are all correct. Can it be that something timed out? What else can I do to trouble shoot?

Many thanks!

**Comment by kylewm** [comment]
Has you app already been approved for "uploadImage"? It's an extended permission:

> Integrations are not permitted to request extended scope from users without explicit prior permission from Medium. Attempting to request these permissions through the standard user authentication flow will result in an error if extended scope has not been authorized for an integration.

**Comment by olgageletina** [comment]
Ah thank you @kylewm! I don't believe it has been approved, the [API documentation](https://github.com/Medium/medium-api-docs) doesn't specify how to go about doing so, do you reckon it's a matter of contacting support?

o

**Comment by kylewm** [comment]
Yep, I think that's your best bet! You can file a request here: https://help.medium.com/hc/en-us/requests/new

**Comment by olgageletina** [comment]
@kylewm I filed a ticket yesterday, and haven't gotten a response. Is there a better process of getting image posting permissions?
