### ISSUE TITLE
Posts generated using the API have different display attributes

### ISSUE THREAD

**Issue by olgageletina** [Medium/medium-api-docs#88]
Posts generated using the API do not display the headings associated with them:
https://medium.com/designscience

While the ones generated using the UI do. It also appears that changing the title/headings in the UI does not reflect on the publication page, e.g. https://medium.com/designscience/1817-6de038d94ccd#.8skt5v864, should have an updated title of "1817 — Farey’s Ellipsograph" 
in the publication (https://medium.com/designscience), but it still says 1817.

**Comment by MediumEng** [comment]
Doing some repo maintenance
