### ISSUE TITLE
Editing/backdating posts for a publication using API

### ISSUE THREAD

**Issue by olgageletina** [Medium/medium-api-docs#89]
Is it possible to edit the PublishedAt date for posts associated with a publication? As the owner of the publication I would like to be able to do that for all of the stories.
https://medium.com/designscience

**Comment by MediumEng** [comment]
There is an undocumented feature to backdate posts using the api by providing "publishedAt": https://github.com/Medium/medium-api-docs/issues/43#issuecomment-184497889
