### ISSUE TITLE
Querying for full list of stories in a publication

### ISSUE THREAD

**Issue by olgageletina** [Medium/medium-api-docs#90]
Similar to #83 and #48, I would like to be able to access all of the stories associated with a publication – whether its through the RSS feed (currently only displays the 10 latest entries) or API.

**Comment by enginebai** [comment]
Hi, I've built this https://github.com/enginebai/PyMedium, Unofficial Medium API.

**Comment by MediumEng** [comment]
There are currently no plans to support a read API

There are no currently plans to support filtering RSS feeds.

Please note that using the private JSON API is against Medium's [terms of service](https://medium.com/policy/medium-terms-of-service-9db0094a1e0f) and could result in loss of access to the site.
