### ISSUE TITLE
Search for posts by title/tag.

### ISSUE THREAD

**Issue by sergiotapia** [Medium/medium-api-docs#91]
Hey Medium, I'd love an endpoint where I can find the recent posts with title containing a string. Or tags include string.

Is there such a feature?

**Comment by j127** [comment]
I'm also looking for some kind of search feature. I only see a way to create posts, not search them. https://github.com/Medium/medium-api-docs#33-posts

**Comment by sjackson212** [comment]
Not to come in late to this, but it's also impossible (as far as I can tell) to get tags back as part of the publication objects returned by the API. Makes tags useless from an API user's standpoint.

**Comment by sergiotapia** [comment]
@ktzhu is this by design?

**Comment by IsNotADeveloper** [comment]
Wanted to drop my two cents on how much more I'd actually use medium if this existed, assuming it doesn't now (I don't see this anywhere in the documentation).

**Comment by MediumEng** [comment]
The are currently no plans to build a read or search API.
