### ISSUE TITLE
Include the relationship "collection"/"type" with each `publication` in `GET https://api.medium.com/v1/users/{{userId}}/publications`

### ISSUE THREAD

**Issue by newhouse** [Medium/medium-api-docs#93]
Hello and thanks for this API - it's very much appreciated!

I have a request (or a question if I'm missing something from the docs). Here's my situation:
I've got a User and I want get information about them that includes what `publications` they are able to publish to. When I make a call to `GET https://api.medium.com/v1/users/{{userId}}/publications` I receive back an array of `publications` (which is nice) but as the documentation says:
> Returns a full list of publications that the user is related to in some way: This includes all publications the user is subscribed to, writes to, or edits.

Each element in the response array gives me no indication of why it's there so I've got no clue whether the User follows, writes or edits that publication. The only way I'm seeing in the documentation to figure out what publications a User can actually publish to is to:
1. Make a call to `GET https://api.medium.com/v1/users/{{userId}}/publications`
2. For **_each and every_** `publication` in the `data` array of the response, make **_another_** call to `GET https://api.medium.com/v1/publications/{{publicationId}}/contributors` to get the contributors for that `publication`.
3. For each result of the above step, search through the array of `contributors` and look for my User.

Am I missing an easier way? Of course I'm biased, but I _think_ that this would sound like a common "question" that one would try to answer via the API. Perhaps if I'm not missing something it would be possible to add more data to each element in the `GET users/{{userId}}/publications` response? Perhaps something like this:
```
{
  "data": [
    {
      "id": "AbCdEfG",
      "name": "somepublication",
      "description": "Lorem ipsum...",
      "url": "https://....",
      "imageUrl": "https://..."
      "collection": "follower" // Enum indicating why this element is in the list.
    },
    {
      "id": "HiJkLmN",
      "name": "anotherpublication",
      "description": "Lorem ipsum...",
      "url": "https://....",
      "imageUrl": "https://..."
      "collection": "staff", // Enum indicating why this element is in the list.
      "role": "writer" // Enum detailing the role on a publication when "collection" === "staff"
    }
```

Just wondering if I need to code the steps I mentioned above, if there's an easier way, or if maybe an easier way could be created?

Thanks - Chris

**Comment by MediumEng** [comment]
There is no easier way that I am aware of. Unfortunately, there are currently no plans for enhancements to the API.
