### ISSUE TITLE
grant_type was invalid

### ISSUE THREAD

**Issue by m1xf1t** [Medium/medium-api-docs#98]
Hi there,

I'm currently stuck trying to authenticate my Medium API with Postman.

I'm following these docs:
https://github.com/Medium/medium-api-docs

**This is what I'm receiving when I send my POST**
{
  "errors": [
    {
      "message": "grant_type was invalid.",
      "code": 6021
    }
  ]
}

**POST:**
Host: https://api.medium.com/v1/tokens
Body: form-data

Any help would be greatly appreciated.

**Comment by dahal** [comment]
@m1xf1t did you solve the issue, I am experiencing the same.

**Comment by newhouse** [comment]
@dahal if you can provide something where I can reproduce the error, I can try and help you. A `curl` command perhaps? If you’re using postman it can convert setups to curl and you can paste it here.

**Comment by newhouse** [comment]
@dahal obviously “x” out any sensitive information and I’ll substitute my own.

**Comment by gnogueira-daitan** [comment]
@newhouse @dahal Same problem here using Postman, I changed to curl and everything worked fine. Not sure what happened.

**Comment by newhouse** [comment]
I've noticed Postman can sometimes be weird like that. If anyone actually needs help, please post a curl command or some other reproduction or nobody can help you.

**Comment by gnogueira-daitan** [comment]
@newhouse it is working fine. Thanks.

**Comment by marharyta** [comment]
@gnogueira-daitan I am using curl but it doesn't work for me. Can you check mine and tell me if something is wrong with it? 
`curl -X POST  'https://api.medium.com/v1/tokens?code=1111111111&client_id=11111111111&client_secret=11111111111111111111111111&grant_type=authorization_code&redirect_uri=https://aito.ai/' -H 'Accept: application/json' -H 'Accept-Charset: utf-8' -H 'Cache-Control: no-cache' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Host: api.medium.com'`

**Comment by marharyta** [comment]
@newhouse Is there any other reason it might not work? neither Postman or Insomnia nor curl works for me.

**Comment by gnogueira-daitan** [comment]
Hi @marharyta, this is my curl command: 

curl -X POST https://api.medium.com/v1/tokens -H "Content-Type: application/x-www-form-urlencoded" -d grant_type=authorization_code -d code=ZZZ
-d client_id=ZZZZ -d client_secret=ZZZ -d redirect_uri=http://webhook.info/post/ZZZZZ

**Comment by newhouse** [comment]
@marharyta to add a bit:

Your curl request is a bit malformed. Since it is a `POST` you need to pass the data (`code`, `client_id`, etc) as part of the data body using the `-d` flags as @gnogueira-daitan has shown (not as query string parameters in the URL after the `?` as you've done in your example).

You can, however, pass them to `curl` in a `-d` all together in a query-string-like format as you've got. For example, here is a `curl` that works for me:

```
curl -X POST \
  https://api.medium.com/v1/tokens \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'code=xxxx&client_id=yyyyyy&client_secret=zzzzz&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fmysite.local%3A5000%2Fauth%2Fmedium%2Fcallback'
```

Also note that the `redirect_uri` parameter (and probably all of them, but this one in particular) should be URL-encoded. These could/should be your problems. Good luck!

**Comment by marharyta** [comment]
@newhouse @gnogueira-daitan thank you, guys!

**Comment by marharyta** [comment]
Here is my curl request now, I get 404:
`curl -X POST https://api.medium.com/v1/tokens  -H 'Accept: application/json' -H 'Accept-Charset: utf-8' -H 'Cache-Control: no-cache' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Host: api.medium.com' -d grant_type=authorization_code -d code=jgfhgfvghjfhgfg -d client_id=jgfjhvhfv -d client_secret=hgfhgfhvhjfgkhbhjbyghjbhjgjh -d redirect_uri=https://aito.ai/
`

**Comment by gnogueira-daitan** [comment]
@marharyta I ran the same code and I got an invalid token error (yeah, sure) so, the problem is with you redirect uri? and remove this 'host' in header.

**Comment by lucaspasquier** [comment]
Hi there,

I'm trying to authenticate my app on Medium API, so I can fetch some data.

I followed all the steps in:
https://github.com/Medium/medium-api-docs

And when I recieve the "code", I try to do another post on the API and I got this same error:

HTTP 400
{"errors":[{"message":"grant_type was invalid.","code":6021}]}

This is my request:

https://api.medium.com/v1/tokens?code=dbc2ede843b6&client_id=XXXXXXXXXXXX&client_secret=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fwww.cesar.org.br

Some one could help me figure it out what am I doing wrong?

**Comment by tr33y4** [comment]
same problem
{"errors":[{"message":"grant_type was invalid.","code":6021}]}
